/* Resource IDs for the resource compiler, generated from enums.h. */
#ifndef STARS_RESOURCE_H
#define STARS_RESOURCE_H

/* DialogId */
#undef IDD_MERGE_FLEETS
#define IDD_MERGE_FLEETS 82
#undef IDD_TRANSFER
#define IDD_TRANSFER 91
#undef IDD_SLOT
#define IDD_SLOT 92
#undef IDD_PRODUCTION
#define IDD_PRODUCTION 93
#undef IDD_ORDER_INFO
#define IDD_ORDER_INFO 97
#undef IDD_SERIAL_NUMBER
#define IDD_SERIAL_NUMBER 86
#undef IDD_ZIP_PROD
#define IDD_ZIP_PROD 89
#undef IDD_ABOUT
#define IDD_ABOUT 90
#undef IDD_HOST_MODE
#define IDD_HOST_MODE 115
#undef IDD_PASSWORD
#define IDD_PASSWORD 140
#undef IDD_NEW_PASSWORD
#define IDD_NEW_PASSWORD 141
#undef IDD_RESEARCH
#define IDD_RESEARCH 127
#undef IDD_BROWSER
#define IDD_BROWSER 128
#undef IDD_RACE_WIZARD_1
#define IDD_RACE_WIZARD_1 146
#undef IDD_RACE_WIZARD_2
#define IDD_RACE_WIZARD_2 147
#undef IDD_RACE_WIZARD_3
#define IDD_RACE_WIZARD_3 148
#undef IDD_RACE_WIZARD_4
#define IDD_RACE_WIZARD_4 149
#undef IDD_RACE_WIZARD_5
#define IDD_RACE_WIZARD_5 150
#undef IDD_RACE_WIZARD_6
#define IDD_RACE_WIZARD_6 151
#undef IDD_VCR
#define IDD_VCR 160
#undef IDD_SIMPLE_NEW_GAME
#define IDD_SIMPLE_NEW_GAME 209
#undef IDD_NEW_GAME_1
#define IDD_NEW_GAME_1 390
#undef IDD_NEW_GAME_2
#define IDD_NEW_GAME_2 391
#undef IDD_NEW_GAME_3
#define IDD_NEW_GAME_3 392
#undef IDD_Gauge
#define IDD_Gauge 393
#undef IDD_HOST_OPTIONS
#define IDD_HOST_OPTIONS 1026
#undef IDD_SCORE
#define IDD_SCORE 102
#undef IDD_BATTLE_PLANS
#define IDD_BATTLE_PLANS 2013
#undef IDD_RENAME
#define IDD_RENAME 2019
#undef IDD_RELATIONS
#define IDD_RELATIONS 2008
#undef IDD_SAVE_TURN1
#define IDD_SAVE_TURN1 1068
#undef IDD_SAVE_TURN2
#define IDD_SAVE_TURN2 2025
#undef IDD_PANIC
#define IDD_PANIC 2504
#undef IDD_TUTOR
#define IDD_TUTOR 2502
#undef IDD_FIND
#define IDD_FIND 4202
#undef IDD_PRINT_MAP
#define IDD_PRINT_MAP 214

/* ControlId */
#undef IDOK
#define IDOK 1
#undef IDCANCEL
#define IDCANCEL 2
#undef IDHELP
#define IDHELP 9
#undef IDC_HELP
#define IDC_HELP 118
#undef IDC_BACK
#define IDC_BACK 1070
#undef IDC_NEXT
#define IDC_NEXT 1071
#undef IDC_FINISH
#define IDC_FINISH 1072
#undef IDC_EDIT1
#define IDC_EDIT1 268
#undef IDC_EDITTEXT
#define IDC_EDITTEXT 268
#undef IDC_EDITNAME
#define IDC_EDITNAME 2075
#undef IDC_PASSWORD_STATUS_TEXT
#define IDC_PASSWORD_STATUS_TEXT 2018
#undef IDC_COMBOBOX
#define IDC_COMBOBOX 2074
#undef IDC_RENAME
#define IDC_RENAME 1051
#undef IDC_IMPORT
#define IDC_IMPORT 2070
#undef IDC_DELETE
#define IDC_DELETE 2071
#undef IDC_EDIT
#define IDC_EDIT 2072
#undef IDC_SHIPLIST
#define IDC_SHIPLIST 1035
#undef IDC_SAVE
#define IDC_SAVE 1065
#undef IDC_SAVESUBMIT
#define IDC_SAVESUBMIT 1066
#undef IDC_NO_DON_T_SAVE
#define IDC_NO_DON_T_SAVE 1067
#undef IDM_DEBUG_DUMP_FLEETS
#define IDM_DEBUG_DUMP_FLEETS 83
#undef IDM_DEBUG_DUMP_PLANETS
#define IDM_DEBUG_DUMP_PLANETS 84
#undef IDM_DEBUG_DUMP_UNIVERSE
#define IDM_DEBUG_DUMP_UNIVERSE 85
#undef IDM_GAME_SCORE
#define IDM_GAME_SCORE 95
#undef IDM_GAME_SCORE2
#define IDM_GAME_SCORE2 96
#undef IDM_HELP_ABOUT
#define IDM_HELP_ABOUT 99
#undef IDM_FLEET_DELETE_WAYPOINT
#define IDM_FLEET_DELETE_WAYPOINT 103
#undef IDM_FLEET_INSERT_WAYPOINT
#define IDM_FLEET_INSERT_WAYPOINT 104
#undef IDM_FILE_HOST_GAME
#define IDM_FILE_HOST_GAME 105
#undef IDM_TURN_WAIT_NEW
#define IDM_TURN_WAIT_NEW 106
#undef IDM_FILE_OPEN_GAME
#define IDM_FILE_OPEN_GAME 109
#undef IDM_FILE_NEW_GAME
#define IDM_FILE_NEW_GAME 110
#undef IDM_FILE_RETURN_TO_TITLE
#define IDM_FILE_RETURN_TO_TITLE 113
#undef IDM_TOOL_NEW_GAME
#define IDM_TOOL_NEW_GAME 3800
#undef IDM_TOOL_OPEN_GAME
#define IDM_TOOL_OPEN_GAME 3801
#undef IDM_GAME_SHIP_BUILDER
#define IDM_GAME_SHIP_BUILDER 125
#undef IDM_GAME_RESEARCH
#define IDM_GAME_RESEARCH 126
#undef IDM_GAME_RELATIONS
#define IDM_GAME_RELATIONS 2009
#undef IDM_GAME_WAIT_FOR_TURN
#define IDM_GAME_WAIT_FOR_TURN 2010
#undef IDM_GAME_BATTLE_PLANS1
#define IDM_GAME_BATTLE_PLANS1 2011
#undef IDM_GAME_BATTLE_PLANS2
#define IDM_GAME_BATTLE_PLANS2 2012
#undef IDM_GAME_RELATIONS2
#define IDM_GAME_RELATIONS2 2014
#undef IDM_VIEW_LAYOUT_0
#define IDM_VIEW_LAYOUT_0 130
#undef IDM_VIEW_LAYOUT_1
#define IDM_VIEW_LAYOUT_1 131
#undef IDM_VIEW_LAYOUT_2
#define IDM_VIEW_LAYOUT_2 132
#undef IDM_VIEW_BROWSER_TOGGLE
#define IDM_VIEW_BROWSER_TOGGLE 136
#undef IDM_VIEW_BROWSER_TOGGLE2
#define IDM_VIEW_BROWSER_TOGGLE2 256
#undef IDM_HELP_CONTENTS
#define IDM_HELP_CONTENTS 138
#undef IDM_HELP_CONTENTS2
#define IDM_HELP_CONTENTS2 257
#undef IDM_RACE_CREATE
#define IDM_RACE_CREATE 129
#undef IDM_RACE_EDIT1
#define IDM_RACE_EDIT1 156
#undef IDM_RACE_EDIT2
#define IDM_RACE_EDIT2 157
#undef IDM_REPORT_PLANET
#define IDM_REPORT_PLANET 2301
#undef IDM_REPORT_CYCLE
#define IDM_REPORT_CYCLE 2302
#undef IDM_REPORT_FLEET
#define IDM_REPORT_FLEET 2303
#undef IDM_REPORT_ENEMY_FLEET
#define IDM_REPORT_ENEMY_FLEET 2304
#undef IDM_REPORT_BATTLE
#define IDM_REPORT_BATTLE 2305
#undef IDM_FILE_MRU1
#define IDM_FILE_MRU1 4300
#undef IDM_FILE_MRU2
#define IDM_FILE_MRU2 4301
#undef IDM_FILE_MRU3
#define IDM_FILE_MRU3 4302
#undef IDM_FILE_MRU4
#define IDM_FILE_MRU4 4303
#undef IDM_FILE_MRU5
#define IDM_FILE_MRU5 4304
#undef IDM_FILE_MRU6
#define IDM_FILE_MRU6 4305
#undef IDM_FILE_MRU7
#define IDM_FILE_MRU7 4306
#undef IDM_FILE_MRU8
#define IDM_FILE_MRU8 4307
#undef IDM_FILE_MRU9
#define IDM_FILE_MRU9 4308
#undef IDM_SCAN_ZOOM_0
#define IDM_SCAN_ZOOM_0 3901
#undef IDM_SCAN_ZOOM_1
#define IDM_SCAN_ZOOM_1 3902
#undef IDM_SCAN_ZOOM_2
#define IDM_SCAN_ZOOM_2 3903
#undef IDM_SCAN_ZOOM_3
#define IDM_SCAN_ZOOM_3 3904
#undef IDM_SCAN_ZOOM_4
#define IDM_SCAN_ZOOM_4 3905
#undef IDM_SCAN_ZOOM_5
#define IDM_SCAN_ZOOM_5 3906
#undef IDM_SCAN_ZOOM_6
#define IDM_SCAN_ZOOM_6 3907
#undef IDM_SCAN_ZOOM_7
#define IDM_SCAN_ZOOM_7 3908
#undef IDM_SCAN_ZOOM_8
#define IDM_SCAN_ZOOM_8 3909
#undef IDM_TURN_END_A
#define IDM_TURN_END_A 3802
#undef IDM_TURN_END_B
#define IDM_TURN_END_B 3803
#undef IDM_POPUP_BASE
#define IDM_POPUP_BASE 15000
#undef IDM_DEBUG_GEN_10_TURNS
#define IDM_DEBUG_GEN_10_TURNS 21000
#undef IDM_DEBUG_GEN_100_TURNS
#define IDM_DEBUG_GEN_100_TURNS 21001
#undef IDM_DEBUG_GEN_1000_TURNS
#define IDM_DEBUG_GEN_1000_TURNS 21002
#undef IDM_VIEW_PLAYER_COLORS
#define IDM_VIEW_PLAYER_COLORS 2445
#undef IDM_UNKNOWN_09C1
#define IDM_UNKNOWN_09C1 2497
#undef IDM_HELP_INTRO
#define IDM_HELP_INTRO 2498
#undef IDM_UNKNOWN_09C4
#define IDM_UNKNOWN_09C4 2500
#undef IDM_HELP_TUTORIAL
#define IDM_HELP_TUTORIAL 2501
#undef IDM_FILE_EXIT
#define IDM_FILE_EXIT 3810
#undef IDM_FRAME_POST_OPEN
#define IDM_FRAME_POST_OPEN 4001
#undef IDM_VIEW_FIND
#define IDM_VIEW_FIND 4200
#undef IDM_UNKNOWN_1069
#define IDM_UNKNOWN_1069 4201
#undef IDM_GAME_RESEARCH2
#define IDM_GAME_RESEARCH2 135
#undef IDM_GAME_SHIP_BUILDER2
#define IDM_GAME_SHIP_BUILDER2 137
#undef IDM_VIEW_GAME_PARAMS
#define IDM_VIEW_GAME_PARAMS 158
#undef IDM_VIEW_GAME_PARAMS2
#define IDM_VIEW_GAME_PARAMS2 159
#undef IDM_VIEW_TOOLBAR
#define IDM_VIEW_TOOLBAR 179
#undef IDM_FILE_PRINT_MAP
#define IDM_FILE_PRINT_MAP 213
#undef IDM_TITLE_NEW_GAME
#define IDM_TITLE_NEW_GAME 250
#undef IDM_TITLE_OPEN_GAME
#define IDM_TITLE_OPEN_GAME 251
#undef IDM_TITLE_CONTINUE
#define IDM_TITLE_CONTINUE 252
#undef IDM_TITLE_EXIT
#define IDM_TITLE_EXIT 253
#undef IDM_CMD_CHANGE_PASSWORD
#define IDM_CMD_CHANGE_PASSWORD 270
#undef IDM_TURN_SAVE_SUBMIT
#define IDM_TURN_SAVE_SUBMIT 1064
#undef WMX_UNKNOWN_0069
#define WMX_UNKNOWN_0069 105
#undef WMX_UNKNOWN_006A
#define WMX_UNKNOWN_006A 106
#undef WMX_UNKNOWN_006C
#define WMX_UNKNOWN_006C 108
#undef WMX_UNKNOWN_006F
#define WMX_UNKNOWN_006F 111

/* CursorId */
#undef IDC_NO_WAY
#define IDC_NO_WAY 121
#undef IDC_TRASH_CAN
#define IDC_TRASH_CAN 122
#undef IDC_RESIZE_WE
#define IDC_RESIZE_WE 258
#undef IDC_RESIZE_NS
#define IDC_RESIZE_NS 260
#undef IDC_RESIZE_4WAY
#define IDC_RESIZE_4WAY 263
#undef IDC_ARROW_HELP
#define IDC_ARROW_HELP 264
#undef IDC_HAND
#define IDC_HAND 265

/* BitmapId */
#undef IDDIB_PLAYER_ICONS_TINY
#define IDDIB_PLAYER_ICONS_TINY 79
#undef IDDIB_PLAYER_ICONS_SMALL
#define IDDIB_PLAYER_ICONS_SMALL 80
#undef IDDIB_THING_ICONS
#define IDDIB_THING_ICONS 87
#undef IDDIB_SCANNER_TOOLBAR
#define IDDIB_SCANNER_TOOLBAR 88
#undef IDDIB_PLANET_ICONS
#define IDDIB_PLANET_ICONS 112
#undef IDB_EMPTY_HULL_SLOT
#define IDB_EMPTY_HULL_SLOT 119
#undef IDDIB_PLAYER_ICONS
#define IDDIB_PLAYER_ICONS 133
#undef IDB_MSGFILTER_CHECKBOX
#define IDB_MSGFILTER_CHECKBOX 134
#undef IDB_TOOLBAR
#define IDB_TOOLBAR 178
#undef IDB_FILTER_CHECKBOX_MONO
#define IDB_FILTER_CHECKBOX_MONO 199
#undef IDB_FONT_DIGITS
#define IDB_FONT_DIGITS 249
#undef IDDIB_SPLASH
#define IDDIB_SPLASH 449
#undef IDB_MINESPAT_1
#define IDB_MINESPAT_1 460
#undef IDB_MINESPAT_2
#define IDB_MINESPAT_2 461
#undef IDB_MINESPAT_3
#define IDB_MINESPAT_3 462
#undef IDDIB_TECH_ICONS_1
#define IDDIB_TECH_ICONS_1 500
#undef IDDIB_TECH_ICONS_2
#define IDDIB_TECH_ICONS_2 501
#undef IDDIB_TECH_ICONS_3
#define IDDIB_TECH_ICONS_3 502
#undef IDDIB_TECH_ICONS_4
#define IDDIB_TECH_ICONS_4 503
#undef IDDIB_TECH_ICONS_5
#define IDDIB_TECH_ICONS_5 504
#undef IDDIB_TECH_ICONS_6
#define IDDIB_TECH_ICONS_6 505
#undef IDDIB_TECH_ICONS_7
#define IDDIB_TECH_ICONS_7 506
#undef IDDIB_HULL_ICONS_1
#define IDDIB_HULL_ICONS_1 552
#undef IDDIB_HULL_ICONS_2
#define IDDIB_HULL_ICONS_2 553
#undef IDDIB_HULL_ICONS_3
#define IDDIB_HULL_ICONS_3 554
#undef IDDIB_HULL_ICONS_4
#define IDDIB_HULL_ICONS_4 555
#undef IDDIB_HULL_ICONS_5
#define IDDIB_HULL_ICONS_5 556
#undef IDDIB_HULL_ICONS_SMALL_1
#define IDDIB_HULL_ICONS_SMALL_1 557
#undef IDDIB_HULL_ICONS_SMALL_2
#define IDDIB_HULL_ICONS_SMALL_2 558
#undef IDDIB_HULL_ICONS_SMALL_3
#define IDDIB_HULL_ICONS_SMALL_3 559
#undef IDDIB_HULL_ICONS_SMALL_4
#define IDDIB_HULL_ICONS_SMALL_4 560
#undef IDDIB_HULL_ICONS_SMALL_5
#define IDDIB_HULL_ICONS_SMALL_5 561
#undef IDDIB_NUM_DESIGNS_PLATE
#define IDDIB_NUM_DESIGNS_PLATE 1079

/* AcceleratorId */
#undef IDA_MAIN
#define IDA_MAIN 116
#undef IDA_TITLE
#define IDA_TITLE 1080

/* TutorialResourceId */
#undef RT_TUTORIAL_HST
#define RT_TUTORIAL_HST 10000
#undef IDR_TUTORIAL_HST
#define IDR_TUTORIAL_HST 10001
#undef RT_TUTORIAL_M1
#define RT_TUTORIAL_M1 10002
#undef IDR_TUTORIAL_M1
#define IDR_TUTORIAL_M1 10003
#undef RT_TUTORIAL_M2
#define RT_TUTORIAL_M2 10004
#undef IDR_TUTORIAL_M2
#define IDR_TUTORIAL_M2 10005

/* MergeFleetsControl */
#undef IDC_MERGE_FLEETS_LIST
#define IDC_MERGE_FLEETS_LIST 81
#undef IDC_MERGE_FLEETS_SELECT_ALL
#define IDC_MERGE_FLEETS_SELECT_ALL 2040
#undef IDC_MERGE_FLEETS_UNSELECT_ALL
#define IDC_MERGE_FLEETS_UNSELECT_ALL 2041

/* ZipProdControl */
#undef IDC_ZIP_PROD_QUEUE
#define IDC_ZIP_PROD_QUEUE 1047
#undef IDC_ZIP_PROD_PRESET_1
#define IDC_ZIP_PROD_PRESET_1 1073
#undef IDC_ZIP_PROD_PRESET_2
#define IDC_ZIP_PROD_PRESET_2 1074
#undef IDC_ZIP_PROD_PRESET_3
#define IDC_ZIP_PROD_PRESET_3 1075
#undef IDC_ZIP_PROD_PRESET_4
#define IDC_ZIP_PROD_PRESET_4 1076

/* AboutControl */
#undef IDC_ABOUT_ORDER_INFO
#define IDC_ABOUT_ORDER_INFO 118
#undef IDC_ABOUT_DEMO_TEXT
#define IDC_ABOUT_DEMO_TEXT 1025
#undef IDC_ABOUT_CREDITS_TEXT
#define IDC_ABOUT_CREDITS_TEXT 1055

/* SlotControl */
#undef IDC_DESIGNER_COMPONENT_LIST
#define IDC_DESIGNER_COMPONENT_LIST 2060
#undef IDC_DESIGNER_SHIPS
#define IDC_DESIGNER_SHIPS 2064
#undef IDC_DESIGNER_STARBASES
#define IDC_DESIGNER_STARBASES 2065
#undef IDC_DESIGNER_EXISTING
#define IDC_DESIGNER_EXISTING 2066
#undef IDC_DESIGNER_HULLS
#define IDC_DESIGNER_HULLS 2067
#undef IDC_DESIGNER_ENEMY_HULLS
#define IDC_DESIGNER_ENEMY_HULLS 2068
#undef IDC_DESIGNER_COMPONENTS
#define IDC_DESIGNER_COMPONENTS 2069

/* ProductionControl */
#undef IDC_PRODUCTION_RESEARCH_LEFTOVERS_ONLY
#define IDC_PRODUCTION_RESEARCH_LEFTOVERS_ONLY 139
#undef IDC_PRODUCTION_AVAILABLE_ITEMS
#define IDC_PRODUCTION_AVAILABLE_ITEMS 1046
#undef IDC_PRODUCTION_QUEUE
#define IDC_PRODUCTION_QUEUE 1047
#undef IDC_PRODUCTION_ADD
#define IDC_PRODUCTION_ADD 1048
#undef IDC_PRODUCTION_REMOVE
#define IDC_PRODUCTION_REMOVE 1049
#undef IDC_PRODUCTION_CLEAR
#define IDC_PRODUCTION_CLEAR 1069
#undef IDC_PRODUCTION_ITEM_UP
#define IDC_PRODUCTION_ITEM_UP 1081
#undef IDC_PRODUCTION_ITEM_DOWN
#define IDC_PRODUCTION_ITEM_DOWN 1082

/* OrderInfoControl */
#undef IDC_ORDER_INFO_TEXT
#define IDC_ORDER_INFO_TEXT 1025

/* ScoreControl */
#undef IDC_SCORE_SWITCH
#define IDC_SCORE_SWITCH 198

/* HostModeControl */
#undef IDC_HOST_GENERATE_NOW
#define IDC_HOST_GENERATE_NOW 1031
#undef IDC_HOST_AUTO_GENERATE
#define IDC_HOST_AUTO_GENERATE 1032
#undef IDC_HOST_GAME_NAME_TEXT
#define IDC_HOST_GAME_NAME_TEXT 1033
#undef IDC_HOST_FILE_TEXT
#define IDC_HOST_FILE_TEXT 1034
#undef IDC_HOST_PASSWORD
#define IDC_HOST_PASSWORD 2015
#undef IDC_HOST_NEXT_YEAR_TEXT
#define IDC_HOST_NEXT_YEAR_TEXT 2016
#undef IDC_HOST_TIME_SINCE_TEXT
#define IDC_HOST_TIME_SINCE_TEXT 2017

/* ResearchControl */
#undef IDC_RESEARCH_ENERGY
#define IDC_RESEARCH_ENERGY 1073
#undef IDC_RESEARCH_WEAPONS
#define IDC_RESEARCH_WEAPONS 1074
#undef IDC_RESEARCH_PROPULSION
#define IDC_RESEARCH_PROPULSION 1075
#undef IDC_RESEARCH_CONSTRUCTION
#define IDC_RESEARCH_CONSTRUCTION 1076
#undef IDC_RESEARCH_ELECTRONICS
#define IDC_RESEARCH_ELECTRONICS 1077
#undef IDC_RESEARCH_BIOTECH
#define IDC_RESEARCH_BIOTECH 1078
#undef IDC_RESEARCH_NEXT_FIELD
#define IDC_RESEARCH_NEXT_FIELD 1083

/* BrowserControl */
#undef IDC_BROWSER_AVAILABLE_ONLY
#define IDC_BROWSER_AVAILABLE_ONLY 266
#undef IDC_BROWSER_COMPONENT_CATEGORY
#define IDC_BROWSER_COMPONENT_CATEGORY 267

/* NewPasswordControl */
#undef IDC_PASSWORD_CONFIRM
#define IDC_PASSWORD_CONFIRM 269

/* RaceWizard1Control */
#undef IDC_RACE_NAME
#define IDC_RACE_NAME 268
#undef IDC_RACE_PASSWORD
#define IDC_RACE_PASSWORD 269
#undef IDC_RACE_HUMANOID
#define IDC_RACE_HUMANOID 271
#undef IDC_RACE_RABBITOID
#define IDC_RACE_RABBITOID 272
#undef IDC_RACE_INSECTOID
#define IDC_RACE_INSECTOID 273
#undef IDC_RACE_NUCLEOTID
#define IDC_RACE_NUCLEOTID 274
#undef IDC_RACE_SILICANOID
#define IDC_RACE_SILICANOID 275
#undef IDC_RACE_ANTETHERAL
#define IDC_RACE_ANTETHERAL 276
#undef IDC_RACE_RANDOM
#define IDC_RACE_RANDOM 277
#undef IDC_RACE_CUSTOM
#define IDC_RACE_CUSTOM 278
#undef IDC_RACE_PLURAL_NAME
#define IDC_RACE_PLURAL_NAME 2075

/* RaceWizard2Control */
#undef IDC_IMMUNE_TO_GRAVITY
#define IDC_IMMUNE_TO_GRAVITY 291
#undef IDC_IMMUNE_TO_TEMPERATURE
#define IDC_IMMUNE_TO_TEMPERATURE 292
#undef IDC_IMMUNE_TO_RADIATION
#define IDC_IMMUNE_TO_RADIATION 293

/* RaceWizard3Control */
#undef IDC_RACE_FACTORY_GERMANIUM_DISCOUNT
#define IDC_RACE_FACTORY_GERMANIUM_DISCOUNT 291

/* RaceWizard4Control */
#undef IDC_RACE_HYPER_EXPANSION
#define IDC_RACE_HYPER_EXPANSION 271
#undef IDC_RACE_SUPER_STEALTH
#define IDC_RACE_SUPER_STEALTH 272
#undef IDC_RACE_WAR_MONGER
#define IDC_RACE_WAR_MONGER 273
#undef IDC_RACE_CLAIM_ADJUSTER
#define IDC_RACE_CLAIM_ADJUSTER 274
#undef IDC_RACE_INNER_STRENGTH
#define IDC_RACE_INNER_STRENGTH 275
#undef IDC_RACE_SPACE_DEMOLITION
#define IDC_RACE_SPACE_DEMOLITION 276
#undef IDC_RACE_PACKET_PHYSICS
#define IDC_RACE_PACKET_PHYSICS 277
#undef IDC_RACE_INTERSTELLAR_TRAVELER
#define IDC_RACE_INTERSTELLAR_TRAVELER 278
#undef IDC_RACE_ALTERNATE_REALITY
#define IDC_RACE_ALTERNATE_REALITY 279
#undef IDC_RACE_JACK_OF_ALL_TRADES
#define IDC_RACE_JACK_OF_ALL_TRADES 280

/* RaceWizard5Control */
#undef IDC_RACE_IMPROVED_FUEL_EFFICIENCY
#define IDC_RACE_IMPROVED_FUEL_EFFICIENCY 291
#undef IDC_RACE_TOTAL_TERRAFORMING
#define IDC_RACE_TOTAL_TERRAFORMING 292
#undef IDC_RACE_ADVANCED_REMOTE_MINING
#define IDC_RACE_ADVANCED_REMOTE_MINING 293
#undef IDC_RACE_IMPROVED_STARBASES
#define IDC_RACE_IMPROVED_STARBASES 294
#undef IDC_RACE_GENERALIZED_RESEARCH
#define IDC_RACE_GENERALIZED_RESEARCH 295
#undef IDC_RACE_ULTIMATE_RECYCLING
#define IDC_RACE_ULTIMATE_RECYCLING 296
#undef IDC_RACE_MINERAL_ALCHEMY
#define IDC_RACE_MINERAL_ALCHEMY 297
#undef IDC_RACE_NO_RAM_SCOOP_ENGINES
#define IDC_RACE_NO_RAM_SCOOP_ENGINES 298
#undef IDC_RACE_CHEAP_ENGINES
#define IDC_RACE_CHEAP_ENGINES 299
#undef IDC_RACE_ONLY_BASIC_REMOTE_MINING
#define IDC_RACE_ONLY_BASIC_REMOTE_MINING 300
#undef IDC_RACE_NO_ADVANCED_SCANNERS
#define IDC_RACE_NO_ADVANCED_SCANNERS 301
#undef IDC_RACE_LOW_STARTING_POPULATION
#define IDC_RACE_LOW_STARTING_POPULATION 302
#undef IDC_RACE_BLEEDING_EDGE_TECHNOLOGY
#define IDC_RACE_BLEEDING_EDGE_TECHNOLOGY 303
#undef IDC_RACE_REGENERATING_SHIELDS
#define IDC_RACE_REGENERATING_SHIELDS 304

/* RaceWizard6Control */
#undef IDC_RACE_ENERGY_COST_EXTRA
#define IDC_RACE_ENERGY_COST_EXTRA 271
#undef IDC_RACE_ENERGY_COST_STANDARD
#define IDC_RACE_ENERGY_COST_STANDARD 272
#undef IDC_RACE_ENERGY_COST_LESS
#define IDC_RACE_ENERGY_COST_LESS 273
#undef IDC_RACE_WEAPONS_COST_EXTRA
#define IDC_RACE_WEAPONS_COST_EXTRA 274
#undef IDC_RACE_WEAPONS_COST_STANDARD
#define IDC_RACE_WEAPONS_COST_STANDARD 275
#undef IDC_RACE_WEAPONS_COST_LESS
#define IDC_RACE_WEAPONS_COST_LESS 276
#undef IDC_RACE_PROPULSION_COST_EXTRA
#define IDC_RACE_PROPULSION_COST_EXTRA 277
#undef IDC_RACE_PROPULSION_COST_STANDARD
#define IDC_RACE_PROPULSION_COST_STANDARD 278
#undef IDC_RACE_PROPULSION_COST_LESS
#define IDC_RACE_PROPULSION_COST_LESS 279
#undef IDC_RACE_CONSTRUCTION_COST_EXTRA
#define IDC_RACE_CONSTRUCTION_COST_EXTRA 280
#undef IDC_RACE_CONSTRUCTION_COST_STANDARD
#define IDC_RACE_CONSTRUCTION_COST_STANDARD 281
#undef IDC_RACE_CONSTRUCTION_COST_LESS
#define IDC_RACE_CONSTRUCTION_COST_LESS 282
#undef IDC_RACE_ELECTRONICS_COST_EXTRA
#define IDC_RACE_ELECTRONICS_COST_EXTRA 283
#undef IDC_RACE_ELECTRONICS_COST_STANDARD
#define IDC_RACE_ELECTRONICS_COST_STANDARD 284
#undef IDC_RACE_ELECTRONICS_COST_LESS
#define IDC_RACE_ELECTRONICS_COST_LESS 285
#undef IDC_RACE_BIOTECH_COST_EXTRA
#define IDC_RACE_BIOTECH_COST_EXTRA 286
#undef IDC_RACE_BIOTECH_COST_STANDARD
#define IDC_RACE_BIOTECH_COST_STANDARD 287
#undef IDC_RACE_BIOTECH_COST_LESS
#define IDC_RACE_BIOTECH_COST_LESS 288
#undef IDC_RACE_START_HIGHER_TECH
#define IDC_RACE_START_HIGHER_TECH 291

/* VcrControl */
#undef IDC_VCR_REW_ALL
#define IDC_VCR_REW_ALL 161
#undef IDC_VCR_REW
#define IDC_VCR_REW 162
#undef IDC_VCR_PLAY_PAUSE
#define IDC_VCR_PLAY_PAUSE 163
#undef IDC_VCR_FWD
#define IDC_VCR_FWD 164
#undef IDC_VCR_FWD_ALL
#define IDC_VCR_FWD_ALL 165

/* SimpleNewGameControl */
#undef IDC_SIMPLE_NEW_GAME_EASY
#define IDC_SIMPLE_NEW_GAME_EASY 200
#undef IDC_SIMPLE_NEW_GAME_STANDARD
#define IDC_SIMPLE_NEW_GAME_STANDARD 201
#undef IDC_SIMPLE_NEW_GAME_HARDER
#define IDC_SIMPLE_NEW_GAME_HARDER 202
#undef IDC_SIMPLE_NEW_GAME_EXPERT
#define IDC_SIMPLE_NEW_GAME_EXPERT 203
#undef IDC_SIMPLE_NEW_GAME_CUSTOMIZE_RACE
#define IDC_SIMPLE_NEW_GAME_CUSTOMIZE_RACE 210
#undef IDC_SIMPLE_NEW_GAME_ADVANCED
#define IDC_SIMPLE_NEW_GAME_ADVANCED 211
#undef IDC_SIMPLE_NEW_GAME_TUTORIAL
#define IDC_SIMPLE_NEW_GAME_TUTORIAL 212
#undef IDC_SIMPLE_NEW_GAME_TINY
#define IDC_SIMPLE_NEW_GAME_TINY 1000
#undef IDC_SIMPLE_NEW_GAME_SMALL
#define IDC_SIMPLE_NEW_GAME_SMALL 1001
#undef IDC_SIMPLE_NEW_GAME_MEDIUM
#define IDC_SIMPLE_NEW_GAME_MEDIUM 1002
#undef IDC_SIMPLE_NEW_GAME_LARGE
#define IDC_SIMPLE_NEW_GAME_LARGE 1003
#undef IDC_SIMPLE_NEW_GAME_HUGE
#define IDC_SIMPLE_NEW_GAME_HUGE 1004

/* PrintMapControl */
#undef IDC_PRINT_MAP_PAGES_X
#define IDC_PRINT_MAP_PAGES_X 268
#undef IDC_PRINT_MAP_PAGES_Y
#define IDC_PRINT_MAP_PAGES_Y 269

/* NewGame1Control */
#undef IDC_NEW_GAME_TINY
#define IDC_NEW_GAME_TINY 1000
#undef IDC_NEW_GAME_SMALL
#define IDC_NEW_GAME_SMALL 1001
#undef IDC_NEW_GAME_MEDIUM
#define IDC_NEW_GAME_MEDIUM 1002
#undef IDC_NEW_GAME_LARGE
#define IDC_NEW_GAME_LARGE 1003
#undef IDC_NEW_GAME_HUGE
#define IDC_NEW_GAME_HUGE 1004
#undef IDC_NEW_GAME_SPARSE
#define IDC_NEW_GAME_SPARSE 1005
#undef IDC_NEW_GAME_NORMAL
#define IDC_NEW_GAME_NORMAL 1006
#undef IDC_NEW_GAME_DENSE
#define IDC_NEW_GAME_DENSE 1007
#undef IDC_NEW_GAME_PACKED
#define IDC_NEW_GAME_PACKED 1008
#undef IDC_NEW_GAME_CLOSE
#define IDC_NEW_GAME_CLOSE 1009
#undef IDC_NEW_GAME_MODERATE
#define IDC_NEW_GAME_MODERATE 1010
#undef IDC_NEW_GAME_FARTHER
#define IDC_NEW_GAME_FARTHER 1011
#undef IDC_NEW_GAME_DISTANT
#define IDC_NEW_GAME_DISTANT 1012
#undef IDC_NEW_GAME_MAX_MINERALS
#define IDC_NEW_GAME_MAX_MINERALS 1016
#undef IDC_NEW_GAME_SLOWER_TECH
#define IDC_NEW_GAME_SLOWER_TECH 1017
#undef IDC_NEW_GAME_ACCELERATED_BBS
#define IDC_NEW_GAME_ACCELERATED_BBS 1018
#undef IDC_NEW_GAME_NO_RANDOM_EVENTS
#define IDC_NEW_GAME_NO_RANDOM_EVENTS 1019
#undef IDC_NEW_GAME_AI_ALLIANCES
#define IDC_NEW_GAME_AI_ALLIANCES 1020
#undef IDC_NEW_GAME_PUBLIC_SCORES
#define IDC_NEW_GAME_PUBLIC_SCORES 1021
#undef IDC_NEW_GAME_NAME
#define IDC_NEW_GAME_NAME 1030
#undef IDC_NEW_GAME_GALAXY_CLUMPING
#define IDC_NEW_GAME_GALAXY_CLUMPING 1050

/* NewGame3Control */
#undef IDC_VC_OWNS_PLANETS
#define IDC_VC_OWNS_PLANETS 291
#undef IDC_VC_TECH_LEVEL
#define IDC_VC_TECH_LEVEL 292
#undef IDC_VC_SCORE
#define IDC_VC_SCORE 293
#undef IDC_VC_SECOND_PLACE
#define IDC_VC_SECOND_PLACE 294
#undef IDC_VC_PRODUCTION
#define IDC_VC_PRODUCTION 295
#undef IDC_VC_CAPITAL_SHIPS
#define IDC_VC_CAPITAL_SHIPS 296
#undef IDC_VC_HIGHEST_SCORE
#define IDC_VC_HIGHEST_SCORE 297

/* GaugeControl */
#undef IDC_GAUGE_TEXT
#define IDC_GAUGE_TEXT 1071

/* HostOptionsControl */
#undef IDC_AUTOGEN_WHEN_ALL_IN
#define IDC_AUTOGEN_WHEN_ALL_IN 1027
#undef IDC_FORCE_GEN_NEVER
#define IDC_FORCE_GEN_NEVER 2066
#undef IDC_FORCE_GEN_OPTION_2
#define IDC_FORCE_GEN_OPTION_2 2067
#undef IDC_FORCE_GEN_OPTION_3
#define IDC_FORCE_GEN_OPTION_3 2068

/* RelationsControl */
#undef IDC_RELATIONS_PLAYER_LIST
#define IDC_RELATIONS_PLAYER_LIST 2003
#undef IDC_RELATIONS_NEUTRAL
#define IDC_RELATIONS_NEUTRAL 2004
#undef IDC_RELATIONS_FRIEND
#define IDC_RELATIONS_FRIEND 2005
#undef IDC_RELATIONS_ENEMY
#define IDC_RELATIONS_ENEMY 2006

/* BattlePlansControl */
#undef IDC_BATTLE_PLAN_COPY
#define IDC_BATTLE_PLAN_COPY 1052
#undef IDC_BATTLE_PLAN_DUMP_CARGO
#define IDC_BATTLE_PLAN_DUMP_CARGO 1053
#undef IDC_BATTLE_PLAN_SELECT
#define IDC_BATTLE_PLAN_SELECT 1054
#undef IDC_BATTLE_PLAN_PRIMARY_TARGET
#define IDC_BATTLE_PLAN_PRIMARY_TARGET 1055
#undef IDC_BATTLE_PLAN_SECONDARY_TARGET
#define IDC_BATTLE_PLAN_SECONDARY_TARGET 1056
#undef IDC_BATTLE_PLAN_TACTIC
#define IDC_BATTLE_PLAN_TACTIC 1057
#undef IDC_BATTLE_PLAN_ATTACK_WHO
#define IDC_BATTLE_PLAN_ATTACK_WHO 1058

/* TutorControl */
#undef IDC_TUTOR_HINT
#define IDC_TUTOR_HINT 118
#undef IDC_TUTOR_PANIC
#define IDC_TUTOR_PANIC 2503

/* PanicControl */
#undef IDC_PANIC_REDO_TURN
#define IDC_PANIC_REDO_TURN 2505
#undef IDC_PANIC_COMPLETE_TURN
#define IDC_PANIC_COMPLETE_TURN 2506

#endif
