#!/usr/bin/env python3
"""Build and run the AutoHotkey v2 tutorial walkthrough in an isolated Wine prefix."""

import argparse
import ast
import configparser
import datetime
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
import zipfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[3]
AHK_VERSION = "2.0.28"
AHK_SHA256 = "b63be7548792b4ad0dfe424d91cc69376694ed2f758245b7a75a0c77d693b478"
AHK_URL = f"https://github.com/AutoHotkey/AutoHotkey/releases/download/v{AHK_VERSION}/AutoHotkey_{AHK_VERSION}.zip"


def prepare_runtime(path, download):
    """prepare_runtime resolves the pinned portable interpreter, verifying downloads before extraction."""
    if path:
        executable = Path(path).resolve()
    else:
        cache = ROOT / "dist/tools/autohotkey"
        executable = cache / f"v{AHK_VERSION}/AutoHotkey64.exe"
        if not executable.is_file() and download:
            cache.mkdir(parents=True, exist_ok=True)
            archive = cache / f"AutoHotkey_{AHK_VERSION}.zip"
            urllib.request.urlretrieve(AHK_URL, archive)
            if hashlib.sha256(archive.read_bytes()).hexdigest() != AHK_SHA256:
                raise ValueError("AutoHotkey archive checksum does not match the pinned release")
            with zipfile.ZipFile(archive) as bundle:
                bundle.extractall(executable.parent)
    if not executable.is_file():
        raise ValueError("AutoHotkey64.exe is missing; use --download-ahk or --ahk PATH")
    return executable


def generate_catalog(stage):
    """generate_catalog exports tutorial instructions and numeric resource constants for the AHK runner."""
    source = (ROOT / "dasm/input/strings_uncompressed.c").read_text()
    source = source.split("const char *const aTUTUncompressed[] = {", 1)[1].split("\n};", 1)[0]
    instructions = {}
    for match in re.finditer(r"/\*\s*(\d+)\s*\([^*]+\*/(.*?)(?=/\*|$)", source, re.S):
        literals = re.findall(r'"(?:[^"\\]|\\.)*"', match[2])
        instructions[int(match[1])] = "".join(ast.literal_eval(value) for value in literals)
    if set(instructions) != set(range(640)):
        raise ValueError("Expected exactly 640 tutorial string fragments (80 pages)")
    with (stage / "instructions.ini").open("w", encoding="utf-8") as output:
        output.write("[Instructions]\n")
        for index, instruction in instructions.items():
            output.write(f"{index}={instruction.strip()}\n")
    defines = {}
    for match in re.finditer(r"^#define\s+(\w+)\s+(0x[0-9A-Fa-f]+|\d+)\s*$", (ROOT / "decompiled/res/resource.h").read_text(), re.M):
        defines[match[1]] = int(match[2], 0)
    defines.update(IDOK=1, IDCANCEL=2)
    with (stage / "controls.ahk").open("w", encoding="utf-8") as output:
        output.write("; Numeric resource constants generated by run.py.\n")
        output.write("global Controls := Map(\n")
        output.write(",\n".join(f'    "{name}", {value}' for name, value in sorted(defines.items())))
        output.write("\n)\n")
    task_source = (ROOT / "decompiled/tutor.c").read_text().split("int16_t FTutorTaskDone() {", 1)[1].split("int16_t FCheck", 1)[0]
    enums = (ROOT / "decompiled/enums.h").read_text()
    tutor_ids = {name: int(value) for name, value in re.findall(r"^\s+(idt\w+) = (\d+),", enums.split("enum TutorId {", 1)[1].split("};", 1)[0], re.M)}
    required = set()
    for assignment in re.findall(r"tutor\.idtBold\s*=\s*([^;]+);", task_source):
        for value in re.findall(r"(?:^|[?:])\s*(\w+)(?=\s*(?:$|:))", assignment):
            if value.isdigit():
                required.add(int(value))
            elif value in tutor_ids:
                required.add(tutor_ids[value])
            else:
                raise ValueError(f"Highlighted tutorial instruction {value} is not a TutorId")
    handled = set()
    for values in re.findall(r"case ([\d, ]+):", (stage / "steps.ahk").read_text()):
        handled.update(int(value) for value in values.split(","))
    if required - handled:
        raise ValueError(f"Highlighted tutorial instructions have no action: {sorted(required - handled)}")
    (stage / "coverage.json").write_text(json.dumps({"pages": 80, "fragments": 640, "required_instructions": sorted(required)}, indent=2) + "\n")
    return instructions


def launcher_failure(run, detail):
    """launcher_failure publishes a failed JSON and JUnit result when the interpreter cannot report one."""
    result = {"status": "failed", "detail": str(detail), "step": "launcher", "actions": 0, "pages": 0}
    suite = ET.Element("testsuite", name="tutorial", tests="1", failures="1")
    case = ET.SubElement(suite, "testcase", name="launcher")
    ET.SubElement(case, "failure", message=str(detail))
    ET.ElementTree(suite).write(run / "results.xml", encoding="utf-8", xml_declaration=True)
    temporary = run / "result.tmp"
    temporary.write_text(json.dumps(result, indent=2) + "\n")
    temporary.replace(run / "result.json")


def stage_ini(source, destination):
    """stage_ini retains supplied registration while resetting tutorial UI and startup settings."""
    settings = configparser.ConfigParser(interpolation=None)
    settings.optionxform = str
    if source:
        settings.read(source)
    registration = settings.get("Windows", "GlobalSettings") if settings.has_option("Windows", "GlobalSettings") else None
    clean = configparser.ConfigParser(interpolation=None)
    clean.optionxform = str
    clean["Windows"] = {"Resolution": "1280x960", "Layout": "1", "Toolbar": "1"}
    if registration:
        clean["Windows"]["GlobalSettings"] = registration
    if not clean.has_section("Misc"):
        clean.add_section("Misc")
    clean["Misc"].update({"Sound": "0", "Music": "0"})
    with destination.open("w") as output:
        clean.write(output, space_around_delimiters=False)


def main():
    """main prepares a unique run, supervises Wine, and requires an explicit test result."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ahk", help="Portable AutoHotkey64.exe (requires v2.0.28)")
    parser.add_argument("--download-ahk", action="store_true", help="Download and verify the pinned official runtime")
    parser.add_argument("--exe", type=Path, help="Existing STARS_TEST_TUTORIAL=ON executable; otherwise build one")
    parser.add_argument("--ini", type=Path, help="Stars.ini supplying registration; other settings are reset")
    parser.add_argument("--work", type=Path, default=ROOT / "dist/scaffold/tutorial", help="Parent directory for retained, unique runs")
    parser.add_argument("--timeout", type=int, default=1800)
    parser.add_argument("--until-year", type=int, choices=range(2400, 2438), help="Stop at a year for development; never reports a full pass")
    parser.add_argument("--scenario", choices=["walkthrough", "reject-generate"], default="walkthrough")
    parser.add_argument("--keep-game-on-failure", action="store_true", help="Keep the isolated game open for debugging a failed action")
    parser.add_argument("--continue-run", type=Path, help="Attach to a retained live game; always reports partial rather than a full pass")
    args = parser.parse_args()
    if args.timeout <= 0:
        parser.error("--timeout must be positive")
    previous_metadata = None
    if args.continue_run:
        metadata_path = args.continue_run / "metadata.json"
        if not metadata_path.is_file():
            parser.error("--continue-run must name a retained run with metadata.json")
        previous_metadata = json.loads(metadata_path.read_text())
        prefix_path = previous_metadata.get("wine_prefix")
        if not isinstance(prefix_path, str) or not prefix_path or not Path(prefix_path).is_absolute():
            parser.error("--continue-run metadata must contain an absolute wine_prefix path")
        prefix = Path(prefix_path)
        if not prefix.is_dir():
            parser.error(f"Retained Wine prefix is missing: {prefix}; /tmp may have been cleared")
    if args.continue_run and args.scenario != "walkthrough":
        parser.error("Live continuation is only available for the walkthrough")
    for command in ("wine", "wineboot", "winepath", "wineserver"):
        if not shutil.which(command):
            parser.error(f"Required command is missing: {command}")
    interpreter = prepare_runtime(args.ahk, args.download_ahk)
    executable = args.exe
    if executable is None:
        build = ROOT / "dist/tutorial-build"
        subprocess.run(["cmake", "--preset", "mingw-debug", "-B", str(build), "-DSTARS_TEST_TUTORIAL=ON"], cwd=ROOT, check=True)
        subprocess.run(["cmake", "--build", str(build), "--parallel", "4"], check=True)
        executable = build / "bin/stars.exe"
    executable = executable.resolve()
    if not executable.is_file():
        parser.error(f"Executable does not exist: {executable}")
    if args.ini and not args.ini.is_file():
        parser.error(f"INI file does not exist: {args.ini}")
    run = args.work.resolve() / datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%S.%fZ")
    stage = run / "game"
    stage.mkdir(parents=True)
    (run / "screenshots").mkdir()
    for script in Path(__file__).parent.glob("*.ahk"):
        shutil.copy2(script, stage / script.name)
    shutil.copy2(executable, stage / "stars.exe")
    generate_catalog(stage)
    if not args.continue_run:
        prefix = Path(tempfile.mkdtemp(prefix="stars-tutorial-", dir="/tmp")).resolve()
    environment = dict(os.environ, WINEPREFIX=str(prefix), WINEDEBUG="-all", MVK_CONFIG_LOG_LEVEL="0",
                       STARS_TUTORIAL_SERIAL=os.environ.get("STARS_TUTORIAL_SERIAL") or "CV6JVUAX")
    print(f"Tutorial run: {run}", flush=True)
    print(f"Wine prefix: {prefix}", flush=True)
    with (run / "wine.log").open("w") as log:
        if not args.continue_run:
            subprocess.run(["wineboot", "-u"], env=environment, stdout=log, stderr=log, check=True, timeout=120)
            ini_source = args.ini
            if ini_source is None:
                local_ini = ROOT / "starsbox/c_drive/WINDOWS/STARS.INI"
                if local_ini.is_file():
                    ini_source = local_ini
            stage_ini(ini_source, prefix / "drive_c/windows/Stars.ini")
        # winepath must share the run's prefix, not the user's default prefix.
        def convert(path):
            """convert translates one staged path using the isolated run environment."""
            return subprocess.check_output(["winepath", "-w", str(path)], env=environment, text=True, stderr=log).strip()
        if not args.continue_run:
            for key, value, data in [(r"HKCU\Software\Wine\Explorer", "Desktop", "StarsTutorial"),
                                     (r"HKCU\Software\Wine\Explorer\Desktops", "StarsTutorial", "1600x1200")]:
                subprocess.run(["wine", "reg", "add", key, "/v", value, "/d", data, "/f"],
                               env=environment, stdout=log, stderr=log, check=True, timeout=30)
        command = ["wine", str(interpreter), "/ErrorStdOut",
                   convert(stage / "tutorial.ahk"), convert(stage), convert(run),
                   str(args.until_year or 2437), args.scenario, str(int(bool(args.continue_run))), str(int(args.keep_game_on_failure))]
        metadata = {"ahk": AHK_VERSION, "wine": subprocess.check_output(["wine", "--version"], text=True).strip(),
                    "wine_prefix": str(prefix),
                    "executable_sha256": (previous_metadata["executable_sha256"]
                                          if args.continue_run else hashlib.sha256(executable.read_bytes()).hexdigest()),
                    "scenario": args.scenario, "until_year": args.until_year, "started": time.time(),
                    "continued_from": str(args.continue_run.resolve()) if args.continue_run else None,
                    "strings_sha256": hashlib.sha256((ROOT / "dasm/input/strings_uncompressed.c").read_bytes()).hexdigest(),
                    "resources_sha256": hashlib.sha256((ROOT / "decompiled/res/stars.rc").read_bytes()).hexdigest()}
        (run / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
        process = subprocess.Popen(command, env=environment, stdout=log, stderr=log)
        deadline = time.monotonic() + args.timeout
        try:
            while not (run / "result.json").exists():
                if " ==> " in (run / "wine.log").read_text(errors="replace"):
                    raise RuntimeError(f"AutoHotkey could not compile the walkthrough; see {run / 'wine.log'}")
                status = process.poll()
                if status is not None:
                    raise RuntimeError(f"Wine exited with status {status}; see {run / 'wine.log'}")
                if time.monotonic() >= deadline:
                    raise RuntimeError(f"Tutorial timed out after {args.timeout}s; see {run}")
                time.sleep(0.25)
        except (RuntimeError, OSError, subprocess.SubprocessError) as error:
            launcher_failure(run, error)
        finally:
            retained_failure = (args.keep_game_on_failure and (run / "result.json").is_file()
                                and json.loads((run / "result.json").read_text())["status"] == "failed")
            if not retained_failure:
                subprocess.run(["wineserver", "-k"], env=environment, stdout=log, stderr=log, timeout=15, check=False)
            try:
                process.wait(timeout=15)
            except subprocess.TimeoutExpired:
                process.kill()
        result = json.loads((run / "result.json").read_text())
    print(json.dumps(result, indent=2))
    print(f"Artifacts: {run}")
    return 0 if result["status"] == "passed" else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (ValueError, RuntimeError, OSError, subprocess.SubprocessError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        sys.exit(1)
