; RunInstruction executes the UI action associated with the highlighted tutorial text.
RunInstruction(bold, state) {
    switch bold {
        case 5: ReadMessages()
        case 11: ClickControl(state["button.1"])
        case 15: PlanetClick("Prune", "Shift")
        case 18, 25, 27, 29, 32, 34: Keys("n")
        case 21: PlanetClick("90210", "Shift")
        case 31: PlanetClick("Alexander", "Shift")
        case 37, 38: Research("Weapons")
        case 39, 47, 95: Generate()
        case 42, 43: ProductionAt("Stove Top", "Factory", 20)
        case 48: MessageGoto()
        case 50: PlanetClick("Hiho", "Shift")
        case 51: PlanetClick("No Vacancy", "Shift")
        case 52: PlanetClick("Slime", "Shift")
        case 53: PlanetClick("Wallaby", "Shift")
        case 54: PlanetClick("Oxygen", "Shift")
        case 55: NextMessage(true)
        case 57: PlanetClick("Dwarte", "Shift")
        case 58: PlanetClick("Mobius", "Shift")
        case 59: PlanetClick("Castle", "Shift")
        case 60: PlanetClick("Mohlodi", "Shift")
        case 61, 63: NextMessage(true)
        case 64: PlanetClick("Shaggy Dog", "Shift")
        case 65: PlanetClick("Sea Squared", "Shift")
        case 66: PlanetClick("Red Storm", "Shift")
        case 67: PlanetClick("Bloop", "Shift")
        case 68: PlanetClick("Kalamazoo", "Shift")
        case 69: NextMessage(true)
        case 71: MessageGoto()
        case 76: FleetSelect(5)
        case 77: PlanetClick("Prune", "Shift")
        case 79: SetTask("Remote Mining")
        case 80: NextMessage(true)
        case 83: ClickPoint(state["hwnd.summary"], 30, 65)
        case 84, 86: NextMessage(true)
        case 89: FleetSelect(2)
        case 90, 91: LoadColonists()
        case 92: PlanetClick("90210", "Shift")
        case 93: SetTask("Colonize")
        case 97, 186, 248: FilterMessage()
        case 216, 238: NextMessage(), FilterMessage()
        case 98: ReadTo(1, true)
        case 101, 102: Production("Factories (Auto Build)", 30)
        case 104: ReadTo(3, true)
        case 106, 107: Production("Factory", 3, 1), Production("Mine", 3, 1)
        case 109: FleetSelect(3)
        case 110, 111, 146, 148: LoadColonists()
        case 112: PlanetClick("90210", "Shift")
        case 113, 164, 277, 473: SetTask("Transport")
        case 114, 170: TransportPreset("QuikDrop")
        case 115: PlanetClick("Hiho")
        case 118: FleetSelect(0)
        case 121: Waypoint(1)
        case 123: DeleteWaypoint(0, 1)
        case 128: ReadTo(0, true)
        case 130: FleetSelect(4)
        case 131, 132: DeleteWaypoint(4, 1)
        case 133: NextMessage(true)
        case 135: PlanetClick("Stove Top", , 2)
        case 136, 137, 173, 174: ProductionAt("Stove Top", "Santa Maria", 1, , 1)
        case 144: FleetSelect(2)
        case 150, 177, 497: ScannerMode(3)
        case 151: PlanetClick("Shaggy Dog", "Shift")
        case 152: SetTask("Colonize")
        case 153, 182: ScannerMode(0)
        case 154: ReadTo(1, true)
        case 155, 166: PlanetClick("Stove Top", "Shift")
        case 156: ReadMessages(), PlanetClick("90210", , 2)
        case 158: DeleteWaypoint(0, 1)
        case 160: FleetSelect(3)
        case 163: PlanetClick("Prune", "Shift")
        case 165: TransportPreset("QuikLoad")
        case 171, 403, 410, 431: RepeatOrders()
        case 176: FleetSelect(6), LoadColonists()
        case 179: PlanetClick("Red Storm", "Shift"), SetTask("Colonize")
        case 181: ProductionAt("Stove Top", "Santa Maria", 3, , 1)
        case 184: ReadTo(3)
        case 187: ReadTo(4, true)
        case 188, 189: Production("Factories (Auto Build)", 10, 1), Production("Mines (Auto Build)", 10, 1)
        case 190, 345, 384, 432, 518: ReadMessages()
        case 192: FleetClick(512), SummaryDetail("fleet")
        case 196: ProductionAt("Stove Top", "Armed Probe", 2, , 2)
        case 200: FleetSelect(7)
        case 202: ClickControl(state["button.8"])
        case 203: TransferShip()
        case 205: Colonize(7, "Slime", true)
        case 206, 515: ClickControl(ReadState()["button.9"])
        case 209: DragWaypoint(7, 1, "Sea Squared")
        case 212: FleetSelect(8)
        case 214: PlanetClick("Hiho", "Shift")
        case 217: ReadMessages(), PlanetClick("Wallaby")
        case 219: SummaryDetail("radiation")
        case 221: Keys("{F5}")
        case 226: ResearchDetails()
        case 228: ResearchBudget(30)
        case 232: ReadTo(0, true)
        case 236: Research("", "Construction")
        case 240: NextMessage(true)
        case 241: FleetSelect(9)
        case 242: LoadColonists()
        case 243: PlanetClick("Oxygen", "Shift"), SetTask("Colonize")
        case 245: DragWaypoint(0, 1, "Mozart")
        case 249: NextMessage(true)
        case 250, 251: Production("Factories (Auto Build)", 3, 1), Production("Mines (Auto Build)", 3, 1)
        case 254, 255, 256, 257: DefaultProductionTemplate(false)
        case 259: ReadTo(3, true)
        case 260: ProductionAt("Stove Top", "Santa Maria", 1, , 1)
        case 262: ProductionAt("Stove Top", "Teamster", 1, , 2)
        case 264: FleetSelect(0)
        case 265: PlanetClick("Hacker", "Shift")
        case 266: ReadTo(1, true)
        case 268: FleetSelect(1), PlanetClick("Stove Top", "Shift"), SetTask("Scrap Fleet")
        case 269: FleetSelect(4), PlanetClick("Stove Top", "Shift")
        case 271: FleetSelect(8), FleetClick(512, "Shift")
        case 272: FleetSelect(2)
        case 274: Colonize(2, "Mozart", true)
        case 275: FleetSelect(11)
        case 276: LoadColonists(), PlanetClick("Wallaby", "Shift")
        case 278, 279: Transport("Unload All")
        case 280: ProductionAt("Stove Top", "Mine", 70, , 0)
        case 281, 282: Research("Construction", "Biotechnology")
        case 283: ReadTo(11, true)
        case 284: CloseBrowser()
        case 418, 450, 542: ReadMessages(), OpenDesigner()
        case 285: ReadTo(13)
        case 286: NextMessage(true)
        case 289, 290: Battle()
        case 291: ReadMessages()
        case 297: ReadTo(1, true)
        case 300:
            point := ObjectPoint(StrSplit(state["fleet.8"], "|")[1], "fleet")
            ClickPoint(point[1], point[2], point[3], , "Right")
            PopupChoice("Salvage")
        case 303: Find("Teamster #4"), FleetSelect(3)
        case 306: ReadTo(5)
        case 308:
            if Integer(state["hwnd.browser"])
                CloseBrowser()
            NextMessage()
        case 310: NextMessage(true)
        case 313: NextMessage(true)
        case 316: Production("Terraform Environment", 2, 1, 0)
        case 318: ProductionAt("Stove Top", "Teamster", 2, , 1)
        case 320: FleetSelect(0), LoadColonists()
        case 321: PlanetClick("Slime", "Shift"), Transport("Unload All")
        case 322: ReadTo(3)
        case 324: Research("Biotechnology", "Propulsion")
        case 325:
            if Integer(state["hwnd.research"])
                ClickId(Integer(state["hwnd.research"]), Controls["IDCANCEL"])
            NextMessage(true)
        case 327:
            if Integer(state["hwnd.browser"])
                CloseBrowser()
            OpenDesigner()
        case 328, 329, 330: CopyHull("Mini-Miner")
        case 332: AddPart("Engines", "Long Hump 6", 0)
        case 333: AddPart("Scanners", "Rhino Scanner", 1)
        case 334, 335: AddPart("Mining Robots", "Robo-Miner", 2), AddPart("Mining Robots", "Robo-Miner", 3)
        case 337, 338: FinishDesign()
        case 339: ProductionAt("Stove Top", "Mini-Miner", 1, , 1)
        case 341, 342: ProductionAt("Stove Top", "Mine", 100, , 0)
        case 344: ProductionTileDetail()
        case 348: FleetSelect(8), PlanetClick("Stove Top", "Shift")
        case 352: ReadTo(0, true)
        case 354: ReadMessages(), MessageGoto()
        case 356: DefaultProductionTemplate(true)
        case 360: FleetSelect(8), PlanetClick("Neil", "Shift")
        case 361: FleetSelect(6), LoadColonists()
        case 363: Keys("{F3}")
        case 364: ReportSort(4, "Sort by Value")
        case 366, 471: CloseReport()
        case 439:
            if Integer(state["hwnd.report"])
                CloseReport()
            WaitFor((s) => s["turnDone"] = "1", "report tutorial tasks completed")
            Generate()
        case 367: FleetSelect(6), PlanetClick("Wallaby", "Shift"), Transport("Unload All")
        case 368, 395: Keys("{F5}")
        case 371, 398: ClickId(WaitDialog("Research"), Controls["IDCANCEL"])
        case 372: ReadMessages(), FleetSelect(11), PlanetClick("Stove Top", "Shift")
        case 376, 488, 552: FleetSelect(4), PlanetClick("Wallaby", "Shift")
        case 378: SetTask("Merge with Fleet"), ClickRect("reference.12", , "Right"), PopupChoice("Cotton Picker #6")
        case 377: FleetSelect(7), PlanetClick("Prune", "Shift"), SetTask("Merge with Fleet")
        case 380, 381: ProductionAt("Stove Top", "Factories (Auto Build)", 30), ProductionAt("Stove Top", "Mines (Auto Build)", 60)
        case 382: Research("Propulsion", "Construction")
        case 385: FleetSelect(0), PlanetClick("Stove Top", "Shift")
        case 392: ProductionAt("Stove Top", "Teamster", 1, , 0)
        case 393: ReadTo(5, true)
        case 396: ResearchDetails()
        case 400: FleetSelect(11), LoadColonists()
        case 401: PlanetClick("Wallaby", "Shift"), Transport("Unload All")
        case 402, 409, 430: PlanetClick("Stove Top", "Shift"), Transport("Load All Available")
        case 406: FleetSelect(1)
        case 407: LoadColonists()
        case 408: PlanetClick("Oxygen", "Shift"), Transport("Unload All")
        case 412: ProductionAt("90210", "Max Terraform (Auto Build)", 1, 1)
        case 413: ReadMessages(), FleetSelect(6), PlanetClick("Stove Top", "Shift")
        case 416: FleetSelect(8), PlanetClick("La Te Da", "Shift")
        case 417: Research("Construction", "Weapons")
        case 419:
            designer := OpenDesigner()
            ClickId(designer, Controls["IDC_DESIGNER_STARBASES"])
            ClickId(designer, Controls["IDC_DESIGNER_EXISTING"])
            SelectIndex(DllCall("GetDlgItem", "ptr", designer, "int", Controls["IDC_COMBOBOX"], "ptr"), 1)
            ClickId(designer, Controls["IDC_IMPORT"])
        case 420: AddPart("Orbital", "Stargate 100/250", 0)
        case 421: FinishDesign("Gater", true)
        case 422: ProductionAt("Stove Top", "Gater", 1, , 1)
        case 424: FleetSelect(0), LoadColonists()
        case 425: PlanetClick("Wallaby", "Shift"), Transport("Unload All")
        case 427, 428: SaveTransportTemplate()
        case 434: Keys("!rp")
        case 435: ReportSort(11, "Reverse Sort by Min Conc", "Weighted Average")
        case 440: FleetSelect(3)
        case 445: TransferFuel(383)
        case 448: ProductionAt("Stove Top", "Teamster", 1, , 1)
        case 449: Research("Weapons", "Propulsion")
        case 451: CopyHull("Frigate")
        case 452: AddPart("Engines", "Daddy Long Legs 7", 0)
        case 453: AddPart("Mine Layers", "Mine Dispenser 50", 2, 3)
        case 454: FinishDesign("Mine Layer")
        case 455: ProductionAt("Stove Top", "Mine Layer", 1, , 2)
        case 456: FleetClick(516)
        case 458: FleetSelect(4)
        case 459: FleetClick(516, "Shift")
        case 464: ReadTo(1, true)
        case 468: ReadTo(2, true)
        case 469: ReportSort(2, "Sort by Population")
        case 472: FleetSelect(6), LoadColonists(), PlanetClick("Sea Squared", "Shift")
        case 474: TransportPreset("DropCol")
        case 475: ReadTo(3), FleetSelect(2)
        case 477: FleetSelect(3)
        case 478, 479: MergeFleet("Teamster #3")
        case 480: FleetSelect(7), Waypoint(0), SetTask("Lay Mine Field")
        case 481: ProductionAt("Stove Top", "Mini-Miner", 1, , 0)
        case 482: ReadTo(14), Battle()
        case 484: FleetSelect(4), Waypoint(0), ClickRect("reference.12", , "Right"), PopupChoice("Berserker Santa Maria #5")
        case 485: ReadMessages(), FleetSelect(8)
        case 486: DragWaypoint(8, 1, "Speed Bump")
        case 487:
            if state["turnDone"] = "1"
                Generate()
            else
                PlanetClick("Lever", "Shift")
        case 489: FleetSelect(2), PlanetClick("Prune", "Shift"), SetTask("Merge with Fleet")
        case 490, 496, 509, 555, 557, 567, 569, 571, 588, 596, 606, 608, 611, 619, 624, 636: LateMessages(bold)
        case 499, 577: OpenDesigner()
        case 500, 501: EditSantaMaria()
        case 502: ReplaceEngine()
        case 503: FinishDesign()
        case 504: ProductionAt("Stove Top", "Santa Maria", 3, , 0)
        case 505: ReadTo(4, true)
        case 507: Production("Max Terraform (Auto Build)", 2, 1)
        case 508: ReadTo(6), Research("Propulsion", "Construction")
        case 512: ReadTo(4)
        case 513: FleetSelect(9)
        case 514: Colonize(9, "Lever", true)
        case 516: DragWaypoint(9, 1, "Speed Bump")
        case 517: DragWaypoint(10, 1, "Bloop")
        case 521: ProductionAt("Stove Top", "Teamster", 3, , 1)
        case 523: FleetClick(517)
        case 525: DragWaypoint(4, 1, 517, "fleet")
        case 528: FleetSelect(4)
        case 530: Waypoint(0), ClickRect("reference.12", , "Right"), PopupChoice("Berserker Santa Maria #6")
        case 532: ReadTo(1, true)
        case 534: FleetSelect(12)
        case 535: LoadColonists()
        case 537: FleetSelect(11), MergeFleet("Teamster #13")
        case 538: ReadTo(8)
        case 540: ReadMessages()
        case 545: CopyHull("Destroyer")
        case 546: BuildDestroyer()
        case 547: AddPart("Mechanical", "Fuel Tank", 5), AddPart("Electrical", "Battle Computer", 6)
        case 549: FinishDesign("", true)
        case 550: ProductionAt("Stove Top", "Destroyer", 10, , 0)
        case 554: PlanetClick("Wallaby", "Shift")
        case 556: FleetSelect(12), PlanetClick("Hacker", "Shift")
        case 560: FleetSelect(3)
        case 562: Waypoint(1), SetWarp(5)
        case 564: ReadTo(6), FleetSelect(13)
        case 565: PlanetClick("Hacker", "Shift")
        case 570: Research("Construction", "Energy")
        case 572: FleetSelect(6)
        case 574: Waypoint(0), SetTask("Scrap Fleet")
        case 578: CopyHull("B-17 Bomber")
        case 579: AddPart("Engines", "Radiating Hydro-Ram Scoop", 0, 2)
        case 580: AddPart("Bombs", "Black Cat Bomb", 1, 4), AddPart("Bombs", "Black Cat Bomb", 2, 4), AddPart("Mechanical", "Fuel Tank", 3)
        case 581: FinishDesign()
        case 582: ProductionAt("Stove Top", "B-17 Bomber", 10, , 0)
        case 586: ReadTo(5), FleetSelect(14)
        case 592: ReadTo(6), PlanetSelect("Wallaby")
        case 594: Production("Mine", 100, 1, 0)
        case 600: ReadTo(2), FleetSelect(12)
        case 602:
            popup := WinExist("ahk_class starspopup ahk_pid " GamePid)
            if !popup
                Choose(state["hwnd.composition"], "Destroyer")
            popup := WinWait("ahk_class starspopup ahk_pid " GamePid, , 3)
            if !popup
                throw Error("Destroyer details did not open")
            WinGetClientPos , , &width, &height, popup
            ClickPoint(popup, width // 2, height // 2)
            WaitFor((s) => s["progress"] = "1", "Destroyer details inspected")
        case 604: ReadTo(18), Battle()
        case 609: Production("B-17 Bomber", 10, , 0)
        case 127, 143, 159, 175, 198, 230, 247, 263, 295, 319, 350, 358, 374, 383, 387: Generate()
        case 399, 414, 423, 461, 492, 511, 527, 551, 559, 583, 590, 598, 612, 628, 637: Generate()
        default: throw Error("Unknown highlighted instruction " bold)
    }
}

; LoadColonists fills the selected fleet's cargo through the real transfer gauge.
LoadColonists() {
    state := ReadState()
    ClickControl(state["button.7"])
    dialog := WaitDialog("Cargo Transfer")
    state := WaitFor((s) => s.Has("transferMode"), "cargo transfer layout")
    for key, value in state {
        if SubStr(key, 1, 15) != "transferButton."
            continue
        gauge := StrSplit(value, "|")
        if gauge[1] = "3" && gauge[2] = "0" && gauge[3] = "0" {
            left := Integer(gauge[5]), top := Integer(gauge[6]), right := Integer(gauge[7]), bottom := Integer(gauge[8])
            from := ClientPoint(dialog, left + 2, (top + bottom) // 2)
            to := ClientPoint(dialog, right - 2, (top + bottom) // 2)
            WinActivate dialog
            MouseClickDrag "Left", from[1], from[2], to[1], to[2], 2
            ClickId(dialog, Controls["IDOK"])
            WinWaitClose dialog, , 5
            return
        }
    }
    throw Error("No colonist cargo gauge was published")
}
